from fastapi import APIRouter
from fastapi.responses import HTMLResponse

from app.pantry_ui import STYLE, TOKEN_JS

router = APIRouter(tags=["Consumption UI"])

HTML = f'''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>库存消耗确认 · Food Assistant</title><style>{STYLE}.review{{margin:14px 0}}.ingredient{{display:grid;grid-template-columns:minmax(150px,2fr) repeat(3,minmax(100px,1fr));gap:8px;align-items:center;border-top:1px solid var(--border);padding:10px 0}}@media(max-width:700px){{.ingredient{{grid-template-columns:1fr}}}}</style></head><body><header><div><h1>库存消耗确认</h1><span class="muted">烹饪完成后，由你确认实际用量</span></div><div><input id="token" type="password" placeholder="Food Assistant API Token"><button onclick="saveToken()">保存令牌</button><a href="/cook">厨房</a> · <a href="/shopping">购物清单</a></div></header><main><div id="error" class="error"></div><div id="reviews"></div></main><script>{TOKEN_JS}
document.querySelector('#token').value=token();let reviews=[];const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}}[c]));
function unitExplanation(p){{const labels={{'exact raw unit':'单位一致','missing unit':'单位缺失','incompatible unit family':'单位不兼容','unsupported free-text unit':'无法识别单位'}};return p.unit_match_reason==='equivalent spelling'?`等价单位：${{p.recipe_unit||'—'}} ↔ ${{p.pantry_unit||'—'}}`:labels[p.unit_match_reason]||''}}
async function load(){{try{{reviews=await api('/api/v1/consumption-reviews?owner=household');render()}}catch(e){{fail(e)}}}}
function render(){{document.querySelector('#reviews').innerHTML=reviews.map(r=>`<section class="panel review" id="review-${{r.id}}"><h2>${{esc(r.recipe_name)}} <span class="status">${{r.status}}</span></h2><p class="muted">完成记录：${{new Date(r.created_at).toLocaleString()}}</p>${{r.status==='pending'?r.proposal.map(p=>row(r,p)).join(''):`<pre>${{esc(JSON.stringify(r.inventory_adjustments,null,2))}}</pre>`}}<div class="actions">${{r.status==='pending'?`<button class="primary" onclick="confirmReview(${{r.id}})">确认库存变化</button><button onclick="dismissReview(${{r.id}})">忽略</button>`:''}}${{r.status==='confirmed'&&!r.inventory_adjustments.some(x=>x.reversed_at)?`<button class="danger" onclick="undo(${{r.id}})">撤销本次调整</button>`:''}}</div></section>`).join('')||'<section class="panel">暂无消耗确认。</section>'}}
function row(r,p){{const options=(p.candidate_pantry_items||[]).map(x=>`<option value="${{x.id}}" ${{x.id===p.matched_pantry_item_id?'selected':''}}>${{esc(x.name)}} · ${{x.quantity??'数量未知'}} ${{esc(x.unit||'')}}</option>`).join('');return `<div class="ingredient" data-review="${{r.id}}" data-index="${{p.recipe_ingredient_index}}"><div><strong>${{esc(p.recipe_ingredient_name)}}</strong><div class="muted">${{esc(p.reason)}}</div><div class="muted">${{esc(unitExplanation(p))}}</div></div><select class="pantry"><option value="">选择库存</option>${{options}}</select><select class="action"><option value="leave_unchanged">不修改</option><option value="deduct" ${{p.suggested_action==='deduct'?'selected':''}} ${{!p.quantity_compatible?'disabled':''}}>扣减</option><option value="consume_all">全部用完</option></select><div><input class="quantity" type="number" min="0.000001" step="any" value="${{p.suggested_deduction??''}}" placeholder="实际数量"><label><input class="shop" type="checkbox"> 低库存/缺货加入清单</label></div></div>`}}
function request(id){{return [...document.querySelectorAll(`[data-review="${{id}}"]`)].map(x=>({{recipe_ingredient_index:Number(x.dataset.index),pantry_item_id:Number(x.querySelector('.pantry').value),action:x.querySelector('.action').value,quantity_used:x.querySelector('.quantity').value?Number(x.querySelector('.quantity').value):null,unit:(reviews.find(r=>r.id===id).proposal.find(p=>p.recipe_ingredient_index===Number(x.dataset.index)).pantry_unit),add_to_shopping_list_if_low:x.querySelector('.shop').checked}})).filter(x=>x.pantry_item_id)}}
async function confirmReview(id){{const items=request(id);if(!confirm('请再次确认：将按预览修改库存并写入审计记录。'))return;try{{await api(`/api/v1/consumption-reviews/${{id}}/confirm`,{{method:'POST',body:JSON.stringify({{owner:'household',confirm_review_id:id,items}})}});load()}}catch(e){{fail(e)}}}}
async function dismissReview(id){{if(!confirm('确认忽略本次库存消耗？'))return;try{{await api(`/api/v1/consumption-reviews/${{id}}/dismiss`,{{method:'POST',body:JSON.stringify({{owner:'household',confirm_review_id:id}})}});load()}}catch(e){{fail(e)}}}}
async function undo(id){{if(!confirm('确认撤销本次库存调整？购物清单项目不会自动删除。'))return;try{{await api(`/api/v1/consumption-reviews/${{id}}/undo`,{{method:'POST',body:JSON.stringify({{owner:'household',confirm_review_id:id}})}});load()}}catch(e){{fail(e)}}}}load();</script></body></html>'''

@router.get("/consumption", response_class=HTMLResponse, include_in_schema=False)
@router.get("/consumption/", response_class=HTMLResponse, include_in_schema=False)
def page() -> HTMLResponse:
    return HTMLResponse(HTML)
