from __future__ import annotations

from fastapi import APIRouter
from fastapi.responses import HTMLResponse


router = APIRouter(tags=["Pantry UI"])

STYLE = """
:root{--bg:#f5f1e8;--panel:#fffdf8;--border:#ddd3c2;--text:#312b23;--muted:#756b5d;--primary:#8a5a2b;--danger:#9b302d;--warn:#956600;--ok:#23643f}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font-family:Inter,'Noto Sans SC','Microsoft YaHei',system-ui,sans-serif}header{padding:18px clamp(16px,4vw,40px);background:var(--panel);border-bottom:1px solid var(--border);display:flex;gap:16px;justify-content:space-between;align-items:center;flex-wrap:wrap}main{max-width:1280px;margin:auto;padding:20px}.panel,.card{background:var(--panel);border:1px solid var(--border);border-radius:12px;padding:15px}.toolbar,.grid,.actions{display:flex;gap:10px;flex-wrap:wrap}.toolbar>*{flex:1;min-width:130px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));margin:14px 0}.summary{font-size:26px;font-weight:700}.muted{color:var(--muted)}input,select,textarea,button{font:inherit;padding:9px 10px;border:1px solid var(--border);border-radius:8px;background:white;color:var(--text)}button{cursor:pointer}button.primary{background:var(--primary);color:white}button.danger{background:var(--danger);color:white}.status{display:inline-block;border-radius:999px;padding:3px 8px;background:#eee}.expired{color:var(--danger);background:#f7e5e3}.expiring{color:var(--warn);background:#f8efd2}.location{margin:22px 0}.error{display:none;background:#f7e5e3;color:var(--danger);padding:12px;border-radius:8px;margin:12px 0;white-space:pre-wrap}dialog{border:1px solid var(--border);border-radius:12px;max-width:520px;width:calc(100% - 24px)}dialog form{display:grid;gap:10px}@media(max-width:600px){main{padding:12px}.actions button{flex:1}.card{padding:12px}}
"""

TOKEN_JS = """
const tokenKey='foodAssistantApiToken';
function token(){return localStorage.getItem(tokenKey)||''}
function saveToken(){localStorage.setItem(tokenKey,document.querySelector('#token').value.trim());load()}
async function api(path,options={}){const headers={...(options.headers||{}),'X-Food-Assistant-Token':token()};if(options.body)headers['Content-Type']='application/json';const r=await fetch(path,{...options,headers});if(!r.ok){let message=`HTTP ${r.status}`;try{const body=await r.json();message=typeof body.detail==='string'?body.detail:JSON.stringify(body.detail)}catch{}throw new Error(message)}return r.status===204?null:r.json()}
function fail(error){const box=document.querySelector('#error');box.textContent=error.message||String(error);box.style.display='block'}
"""


@router.get("/pantry", response_class=HTMLResponse, include_in_schema=False)
@router.get("/pantry/", response_class=HTMLResponse, include_in_schema=False)
def pantry_page() -> HTMLResponse:
    return HTMLResponse(PANTRY_HTML)


@router.get("/recommendations", response_class=HTMLResponse, include_in_schema=False)
@router.get("/recommendations/", response_class=HTMLResponse, include_in_schema=False)
def recommendations_page() -> HTMLResponse:
    return HTMLResponse(RECOMMENDATIONS_HTML)


PANTRY_HTML = f'''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>库存管理 · Food Assistant</title><style>{STYLE}</style></head><body>
<header><div><h1>库存管理</h1><span class="muted">库存 → 菜谱推荐</span></div><div><input id="token" type="password" placeholder="Food Assistant API Token"><button onclick="saveToken()">保存令牌</button><a href="/recommendations">推荐</a></div></header><main><div id="error" class="error"></div>
<section id="summary" class="grid"></section><section class="panel toolbar"><input id="q" placeholder="搜索食材" oninput="loadItems()"><select id="location" onchange="loadItems()"><option value="">全部位置</option><option>fridge</option><option>freezer</option><option>pantry</option><option>other</option></select><select id="state" onchange="loadItems()"><option value="">全部状态</option><option value="expired">过期</option><option value="low">低库存</option><option value="staple">常备品</option></select><button class="primary" onclick="edit()">添加库存</button></section><div id="groups"></div></main>
<dialog id="editor"><form method="dialog" onsubmit="submitItem(event)"><h2 id="editorTitle">库存</h2><input type="hidden" id="id"><label>名称<input id="name" required maxlength="120"></label><label>数量（留空表示有库存但未记录数量）<input id="quantity" type="number" min="0" step="any"></label><label>单位<input id="unit"></label><label>位置<select id="editLocation"><option>fridge</option><option>freezer</option><option selected>pantry</option><option>other</option></select></label><label>过期日期<input id="expires" type="date"></label><label>低库存阈值<input id="threshold" type="number" min="0" step="any"></label><label>owner<input id="owner" value="household"></label><label><input id="staple" type="checkbox"> 常备品</label><div class="actions"><button type="button" onclick="editor.close()">取消</button><button class="primary">保存</button></div></form></dialog>
<dialog id="restock"><form method="dialog" onsubmit="submitRestock(event)"><h2>补货</h2><input type="hidden" id="restockId"><label>数量<input id="restockQuantity" type="number" min="0" step="any"></label><label>单位<input id="restockUnit"></label><label>购买日期<input id="purchased" type="date"></label><label>过期日期<input id="restockExpires" type="date"></label><div class="actions"><button type="button" onclick="restock.close()">取消</button><button class="primary">补货</button></div></form></dialog>
<script>{TOKEN_JS}
const locations={{fridge:'冰箱',freezer:'冷冻',pantry:'储藏室',other:'其他'}};let items=[];document.querySelector('#token').value=token();
function value(id){{return document.querySelector(id).value}} function nullableNumber(v){{return v===''?null:Number(v)}}
async function load(){{document.querySelector('#error').style.display='none';try{{const [s]=await Promise.all([api('/api/v1/inventory/summary'),loadItems()]);const cards=[['总库存',s.total_items],['临期',s.expiring_within_3_days],['过期',s.expired_items],['缺货',s.out_of_stock_items],['低库存',s.low_stock_items]];document.querySelector('#summary').innerHTML=cards.map(x=>`<div class="card"><div class="muted">${{x[0]}}</div><div class="summary">${{x[1]}}</div></div>`).join('')}}catch(e){{fail(e)}}}}
async function loadItems(){{try{{const params=new URLSearchParams({{q:value('#q'),location:value('#location'),include_expired:'true'}});if(value('#state')==='low')params.set('low_stock','true');if(value('#state')==='staple')params.set('staple','true');items=await api('/api/v1/inventory?'+params);if(value('#state')==='expired')items=items.filter(x=>x.is_expired);render()}}catch(e){{fail(e)}}}}
function render(){{document.querySelector('#groups').innerHTML=Object.entries(locations).map(([key,label])=>{{const rows=items.filter(x=>x.location===key);return `<section class="location"><h2>${{label}} <small class="muted">${{rows.length}}</small></h2><div class="grid">${{rows.map(card).join('')||'<span class="muted">暂无库存</span>'}}</div></section>`}}).join('')}}
function card(x){{const qty=x.quantity===null?'有库存，数量未记录':x.quantity===0?'缺货':`${{x.quantity}} ${{x.unit||''}}`;const status=x.is_expired?'<span class="status expired">已过期</span>':x.days_until_expiry!==null&&x.days_until_expiry<=3?'<span class="status expiring">临期</span>':'';return `<article class="card"><h3>${{x.name}} ${{status}}</h3><p>${{qty}}</p><p class="muted">${{x.owner}}${{x.opened?' · 已开封':''}}${{x.is_staple?' · 常备品':''}}</p><div class="actions"><button onclick="edit(${{x.id}})">编辑</button><button onclick="action(${{x.id}},'consume')">吃完</button><button onclick="showRestock(${{x.id}})">补货</button>${{x.opened?'':`<button onclick="action(${{x.id}},'open')">开封</button>`}}<button class="danger" onclick="removeItem(${{x.id}})">删除</button></div></article>`}}
function edit(id){{const x=items.find(i=>i.id===id)||{{}};document.querySelector('#id').value=x.id||'';for(const [selector,key] of [['#name','name'],['#quantity','quantity'],['#unit','unit'],['#expires','expires_at'],['#threshold','low_stock_threshold'],['#owner','owner']])document.querySelector(selector).value=x[key]??(key==='owner'?'household':'');document.querySelector('#editLocation').value=x.location||'pantry';document.querySelector('#staple').checked=!!x.is_staple;editor.showModal()}}
async function submitItem(e){{e.preventDefault();const id=value('#id'),body={{name:value('#name'),quantity:nullableNumber(value('#quantity')),unit:value('#unit')||null,location:value('#editLocation'),expires_at:value('#expires')||null,low_stock_threshold:nullableNumber(value('#threshold')),owner:value('#owner'),is_staple:document.querySelector('#staple').checked}};try{{await api('/api/v1/inventory'+(id?'/'+id:''),{{method:id?'PATCH':'POST',body:JSON.stringify(body)}});editor.close();load()}}catch(error){{fail(error)}}}}
async function action(id,name){{try{{await api(`/api/v1/inventory/${{id}}/${{name}}`,{{method:'POST'}});load()}}catch(e){{fail(e)}}}} function showRestock(id){{document.querySelector('#restockId').value=id;restock.showModal()}}
async function submitRestock(e){{e.preventDefault();try{{await api(`/api/v1/inventory/${{value('#restockId')}}/restock`,{{method:'POST',body:JSON.stringify({{quantity:nullableNumber(value('#restockQuantity')),unit:value('#restockUnit')||null,purchased_at:value('#purchased')||null,expires_at:value('#restockExpires')||null}})}});restock.close();load()}}catch(error){{fail(error)}}}}
async function removeItem(id){{if(!confirm('确定永久删除这条库存记录吗？'))return;try{{await api('/api/v1/inventory/'+id,{{method:'DELETE'}});load()}}catch(e){{fail(e)}}}} load();</script></body></html>'''

RECOMMENDATIONS_HTML = f'''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>菜谱推荐 · Food Assistant</title><style>{STYLE}</style></head><body><header><div><h1>菜谱推荐</h1><span class="muted">根据现有库存透明评分</span></div><div><input id="token" type="password" placeholder="Food Assistant API Token"><button onclick="saveToken()">保存令牌</button><a href="/pantry">库存</a></div></header><main><div id="error" class="error"></div><section class="panel toolbar"><label>最大缺失<input id="missing" type="number" min="0" value="2"></label><label>最大时间（分钟）<input id="time" type="number" min="1"></label><label>分类<input id="category"></label><label>菜系<input id="cuisine"></label><label>owner<input id="owner" value="household"></label><button class="primary" onclick="load(true)">换一批</button></section><div id="results"></div></main><script>{TOKEN_JS}document.querySelector('#token').value=token();let batch=0;const sections={{ready_now:'现在就能做',missing_one_or_two:'只缺一两样',use_soon:'优先消耗临期食材',random_pick:'随机吃什么'}};
async function load(shuffle=false){{document.querySelector('#error').style.display='none';try{{if(shuffle)batch++;const p=new URLSearchParams({{limit:'10',max_missing:document.querySelector('#missing').value||'2',owner:document.querySelector('#owner').value,randomize:String(shuffle),seed:String(Date.now()+batch)}});for(const id of ['time','category','cuisine'])if(document.querySelector('#'+id).value)p.set(id==='time'?'max_total_time':id,document.querySelector('#'+id).value);const data=await api('/api/v1/recommendations?'+p);document.querySelector('#results').innerHTML=Object.entries(sections).map(([key,title])=>`<section class="location"><h2>${{title}}</h2><div class="grid">${{data[key].map(card).join('')||'<span class="muted">暂无符合条件的菜谱</span>'}}</div></section>`).join('')}}catch(e){{fail(e)}}}}
function card(x){{const explanation=x.score_reasons.join('；')+(x.missing_ingredients.length?`；缺少${{x.missing_ingredients.join('、')}}。`:'。');return `<article class="card"><h3>${{x.name}}</h3><p>${{explanation}}</p><p class="muted">评分 ${{x.score}} · ${{x.total_time_minutes??'时间未知'}} 分钟 · ${{x.category||'未分类'}} · ${{x.cuisine||'菜系未知'}}</p><div class="actions"><a href="${{x.mealie_url}}" target="_blank" rel="noopener">打开 Mealie</a><button class="primary" onclick='cooked(${{JSON.stringify(x)}})'>标记今天做了</button></div></article>`}}
async function cooked(x){{try{{await api('/api/v1/cooking-history',{{method:'POST',body:JSON.stringify({{mealie_slug:x.slug,recipe_name:x.name,cooked_at:new Date().toISOString().slice(0,10),owner:document.querySelector('#owner').value||'household'}})}});load()}}catch(e){{fail(e)}}}}load();</script></body></html>'''
