from fastapi import APIRouter
from fastapi.responses import HTMLResponse

from app.pantry_ui import STYLE, TOKEN_JS

router = APIRouter(tags=["Shopping UI"])

HTML = f'''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>购物清单 · Food Assistant</title><style>{STYLE}
.quick-add{{margin-bottom:12px}}.tabs{{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}}.tab{{background:var(--panel);border:2px solid var(--border);font-weight:600}}.tab.active-tab{{background:var(--primary);color:white;border-color:var(--primary);box-shadow:0 2px 8px #8a5a2b44}}.item{{margin:10px 0;display:flex;justify-content:space-between;gap:12px;align-items:center}}.item-main{{min-width:0}}.item-meta{{display:flex;gap:7px;flex-wrap:wrap;align-items:center}}.status-label{{display:inline-block;border-radius:999px;padding:3px 8px;background:#eee;font-size:.9rem}}.status-active{{background:#f8efd2;color:var(--warn)}}.status-completed{{background:#e2f2e8;color:var(--ok)}}.status-dismissed{{background:#eee;color:var(--muted)}}.feedback{{display:none;background:#e2f2e8;color:var(--ok);padding:10px;border-radius:8px;margin:10px 0}}.list-heading{{margin:20px 0 8px}}@media(max-width:600px){{.item{{display:block}}.item .actions{{margin-top:12px}}.tabs .tab{{flex:1;min-width:96px}}}}
</style></head><body><header><div><h1>购物清单</h1><span class="muted">本地清单，不连接外部购物平台</span></div><div><input id="token" type="password" placeholder="Food Assistant API Token"><button onclick="saveToken()">保存令牌</button><a href="/cook">厨房</a> · <a href="/pantry">库存</a> · <a href="/recommendations">推荐</a></div></header><main><div id="error" class="error"></div><div id="feedback" class="feedback" role="status"></div>
<section class="panel toolbar quick-add"><input id="name" placeholder="快速添加食材"><input id="quantity" type="number" min="0" step="any" placeholder="数量"><input id="unit" placeholder="单位"><select id="priority" aria-label="优先级"><option value="normal">普通</option><option value="high">高</option><option value="low">低</option></select><button class="primary" onclick="add()">添加</button></section>
<nav class="tabs" aria-label="购物清单分页"><button id="tab-active" class="tab active-tab" aria-pressed="true" onclick="load('active')">待购买 <span id="count-active">0</span></button><button id="tab-completed" class="tab" aria-pressed="false" onclick="load('completed')">已完成 <span id="count-completed">0</span></button><button id="tab-dismissed" class="tab" aria-pressed="false" onclick="load('dismissed')">已忽略 <span id="count-dismissed">0</span></button></nav>
<h2 id="list-title" class="list-heading">待购买项目</h2><div id="items"></div></main>
<dialog id="restock"><form method="dialog" onsubmit="complete(event)"><h2>完成购买并补货</h2><input id="completeId" type="hidden"><label>库存处理<select id="mode"><option value="none">不更新库存</option><option value="existing">补充现有库存</option><option value="create">创建新库存</option></select></label><label>现有库存 ID<input id="pantryId" type="number"></label><label>数量<input id="restockQty" type="number" min="0" step="any"></label><label>单位<input id="restockUnit"></label><label>位置<input id="location" value="pantry"></label><div class="actions"><button type="button" onclick="restock.close()">取消</button><button class="primary">二次确认完成</button></div></form></dialog><script>{TOKEN_JS}
document.querySelector('#token').value=token();
let current='active';
const statuses={{active:'待购买',completed:'已完成',dismissed:'已忽略'}};
const emptyText={{active:'暂无待购买项目',completed:'暂无已完成项目',dismissed:'暂无已忽略项目'}};
const priorities={{high:'高',normal:'普通',low:'低'}};
const sources={{manual:'手动',low_stock:'低库存',out_of_stock:'缺货',recipe_missing:'菜谱缺失',consumption_review:'烹饪消耗确认'}};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}}[c]));
function updateTabs(){{for(const status of Object.keys(statuses)){{const button=document.querySelector('#tab-'+status),selected=status===current;button.classList.toggle('active-tab',selected);button.setAttribute('aria-pressed',String(selected))}}document.querySelector('#list-title').textContent=statuses[current]+'项目'}}
function localTime(value){{return value?new Date(value).toLocaleString():''}}
function actions(x){{if(x.status==='active')return `<button onclick="showComplete(${{x.id}},${{x.pantry_item_id||'null'}})">完成购买</button><button onclick="dismiss(${{x.id}})">忽略</button>`;return `<button onclick="restore(${{x.id}})">恢复到待购买</button><button class="danger" onclick="deleteItem(${{x.id}})">永久删除</button>`}}
function card(x){{const timestamp=x.status==='completed'&&x.completed_at?`<div class="muted">完成于 ${{esc(localTime(x.completed_at))}}</div>`:x.status==='dismissed'&&x.dismissed_at?`<div class="muted">忽略于 ${{esc(localTime(x.dismissed_at))}}</div>`:'';return `<article class="card item"><div class="item-main"><div class="item-meta"><strong>${{esc(x.name)}}</strong><span class="status-label status-${{x.status}}">${{statuses[x.status]||esc(x.status)}}</span></div><p>${{x.quantity??'数量未定'}} ${{esc(x.unit||'')}}</p><div class="muted">优先级：${{priorities[x.priority]||esc(x.priority)}} · 来源：${{sources[x.source]||esc(x.source)}}</div>${{timestamp}}</div><div class="actions">${{actions(x)}}</div></article>`}}
function render(xs){{document.querySelector('#items').innerHTML=xs.map(card).join('')||`<section class="panel muted">${{emptyText[current]}}</section>`}}
async function load(status=current){{current=status;updateTabs();document.querySelector('#error').style.display='none';try{{const [active,completed,dismissed]=await Promise.all(['active','completed','dismissed'].map(value=>api(`/api/v1/shopping-list?owner=household&status=${{value}}`)));const groups={{active,completed,dismissed}};for(const value of Object.keys(groups))document.querySelector('#count-'+value).textContent=groups[value].length;render(groups[current])}}catch(e){{fail(e)}}}}
async function add(){{document.querySelector('#error').style.display='none';try{{const result=await api('/api/v1/shopping-list',{{method:'POST',body:JSON.stringify({{owner:'household',name:document.querySelector('#name').value,quantity:document.querySelector('#quantity').value?Number(document.querySelector('#quantity').value):null,unit:document.querySelector('#unit').value||null,priority:document.querySelector('#priority').value,source:'manual'}})}});for(const id of ['#name','#quantity','#unit'])document.querySelector(id).value='';await load('active');const box=document.querySelector('#feedback');box.textContent=result.created?'已新增购物项。':'已合并到现有购物项。';box.style.display='block'}}catch(e){{fail(e)}}}}
function showComplete(id,pantryId){{document.querySelector('#completeId').value=id;document.querySelector('#pantryId').value=pantryId||'';restock.showModal()}}
async function complete(e){{e.preventDefault();const id=Number(document.querySelector('#completeId').value);if(!confirm('确认完成购买并执行所选库存操作？'))return;try{{await api(`/api/v1/shopping-list/${{id}}/complete`,{{method:'POST',body:JSON.stringify({{owner:'household',confirm_item_id:id,restock:{{mode:document.querySelector('#mode').value,pantry_item_id:document.querySelector('#pantryId').value?Number(document.querySelector('#pantryId').value):null,quantity:document.querySelector('#restockQty').value?Number(document.querySelector('#restockQty').value):null,unit:document.querySelector('#restockUnit').value||null,location:document.querySelector('#location').value}}}})}});restock.close();await load(current)}}catch(e){{fail(e)}}}}
async function act(id,name){{try{{await api(`/api/v1/shopping-list/${{id}}/${{name}}`,{{method:'POST',body:JSON.stringify({{owner:'household',confirm_item_id:id}})}});await load(current)}}catch(e){{fail(e)}}}}
async function deleteItem(id){{if(!confirm('确认永久删除该购物项吗？此操作不能撤销。'))return;try{{await api(`/api/v1/shopping-list/${{id}}?owner=household`,{{method:'DELETE'}});await load(current)}}catch(e){{fail(e)}}}}
const dismiss=id=>act(id,'dismiss'),restore=id=>act(id,'restore');updateTabs();load('active');</script></body></html>'''

@router.get("/shopping", response_class=HTMLResponse, include_in_schema=False)
@router.get("/shopping/", response_class=HTMLResponse, include_in_schema=False)
def page() -> HTMLResponse:
    return HTMLResponse(HTML)
