from fastapi import APIRouter
from fastapi.responses import HTMLResponse

from app.pantry_ui import STYLE, TOKEN_JS

router = APIRouter(tags=["Shopping UI"])

HTML = f'''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>购物清单 · Food Assistant</title><style>{STYLE}.item{{margin:10px 0;display:flex;justify-content:space-between;gap:12px;align-items:center}}@media(max-width:600px){{.item{{display:block}}}}</style></head><body><header><div><h1>购物清单</h1><span class="muted">本地清单，不连接外部购物平台</span></div><div><input id="token" type="password" placeholder="Food Assistant API Token"><button onclick="saveToken()">保存令牌</button><a href="/cook">厨房</a> · <a href="/pantry">库存</a> · <a href="/recommendations">推荐</a></div></header><main><div id="error" class="error"></div><section class="panel toolbar"><input id="name" placeholder="快速添加食材"><input id="quantity" type="number" min="0" step="any" placeholder="数量"><input id="unit" placeholder="单位"><select id="priority"><option>normal</option><option>high</option><option>low</option></select><button class="primary" onclick="add()">添加</button><button onclick="load('active')">当前</button><button onclick="load('completed')">历史</button><button onclick="load('dismissed')">已忽略</button></section><div id="items"></div></main><dialog id="restock"><form method="dialog" onsubmit="complete(event)"><h2>完成购买并补货</h2><input id="completeId" type="hidden"><label>库存处理<select id="mode"><option value="none">不更新库存</option><option value="existing">补充现有库存</option><option value="create">创建新库存</option></select></label><label>现有库存 ID<input id="pantryId" type="number"></label><label>数量<input id="restockQty" type="number" min="0" step="any"></label><label>单位<input id="restockUnit"></label><label>位置<input id="location" value="pantry"></label><div class="actions"><button type="button" onclick="restock.close()">取消</button><button class="primary">二次确认完成</button></div></form></dialog><script>{TOKEN_JS}
document.querySelector('#token').value=token();let current='active';const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}}[c]));async function load(status=current){{current=status;try{{const xs=await api(`/api/v1/shopping-list?owner=household&status=${{status}}`);document.querySelector('#items').innerHTML=xs.map(x=>`<article class="card item"><div><strong>${{esc(x.name)}}</strong> · ${{x.quantity??'数量未定'}} ${{esc(x.unit||'')}}<div class="muted">${{x.priority}} · ${{x.source}}</div></div><div class="actions">${{x.status==='active'?`<button onclick="showComplete(${{x.id}},${{x.pantry_item_id||'null'}})">完成购买</button><button onclick="dismiss(${{x.id}})">忽略</button>`:`<button onclick="restore(${{x.id}})">恢复</button>`}}</div></article>`).join('')||'<section class="panel">暂无项目。</section>'}}catch(e){{fail(e)}}}}
async function add(){{try{{await api('/api/v1/shopping-list',{{method:'POST',body:JSON.stringify({{owner:'household',name:document.querySelector('#name').value,quantity:document.querySelector('#quantity').value?Number(document.querySelector('#quantity').value):null,unit:document.querySelector('#unit').value||null,priority:document.querySelector('#priority').value,source:'manual'}})}});load()}}catch(e){{fail(e)}}}}function showComplete(id,pantryId){{document.querySelector('#completeId').value=id;document.querySelector('#pantryId').value=pantryId||'';restock.showModal()}}
async function complete(e){{e.preventDefault();const id=Number(document.querySelector('#completeId').value);if(!confirm('确认完成购买并执行所选库存操作？'))return;try{{await api(`/api/v1/shopping-list/${{id}}/complete`,{{method:'POST',body:JSON.stringify({{owner:'household',confirm_item_id:id,restock:{{mode:document.querySelector('#mode').value,pantry_item_id:document.querySelector('#pantryId').value?Number(document.querySelector('#pantryId').value):null,quantity:document.querySelector('#restockQty').value?Number(document.querySelector('#restockQty').value):null,unit:document.querySelector('#restockUnit').value||null,location:document.querySelector('#location').value}}}})}});restock.close();load()}}catch(e){{fail(e)}}}}
async function act(id,name){{try{{await api(`/api/v1/shopping-list/${{id}}/${{name}}`,{{method:'POST',body:JSON.stringify({{owner:'household',confirm_item_id:id}})}});load()}}catch(e){{fail(e)}}}}const dismiss=id=>act(id,'dismiss'),restore=id=>act(id,'restore');load();</script></body></html>'''

@router.get("/shopping", response_class=HTMLResponse, include_in_schema=False)
@router.get("/shopping/", response_class=HTMLResponse, include_in_schema=False)
def page() -> HTMLResponse:
    return HTMLResponse(HTML)
